import "./works.scss"
import { useState } from "react"

export default function Works() {
    const [currentSlide, setCurrentSlide] = useState(0);
    const data = [
        {
            id: "1",
            icon: "assests/web.png",
            title: "CSP: Web Application",
            desc: "A virtual store website where you have to sign in or register an account to buy either a PC or a smartphone. Responsive site with the ability to add products automatically, the site was built using advanced technologies such as NodeJS for backend and HTML5 for frontend and bootstrap for site responsiveness so that it allows a comfortable user experience for surfers on one of the smart devices like tablet or smartphone.",
            img: "assests/CSP.png",
            technologies: ["HTML 5", "CSS", "EJS", "NODEJS", "JAVASCRIPT"]
        },
        {
            id: "4",
            icon: "assests/web.png",
            title: "Semantic Similarity",
            desc: "A desktop application that calculates the similarity between two Arabic sentences/books, the system developed as a final project in my studies. The system is based on a siamese neural network model that contains different layers, such as LSTM, attention, and MLP layers. The Keras python library was chosen to complete this project in addition to much more advanced libraries like NumPy, Matplotlib, Gensim, and many more.",
            img: "assests/Semantic Similarity.png",
            technologies: ["HTML 5", "CSS", "EJS", "NODEJS", "JAVASCRIPT"]

        },

        {
            id: "2",
            icon: "assests/java.png",
            title: "Information Security And Cryptography",
            desc: "Secure remote access to a dataset of hash files, a user password is used to access the data and the key generated by the RSA encryption system which is also used to decrypt the files that have been encrypted by the TEA encryption system.",
            img: "assests/Crypto.png",
            technologies: ["JAVA", "TEA (TINY ENCRYPTION ALGORITHM)", "RSA (RIVEST–SHAMIR–ADLEMAN ALGORITHM)", "SHA-1"]

        },
        {
            id: "3",
            icon: "assests/mobile.png",
            title: "Task Management",
            desc: "A responsive web application for managing tasks, where the user can add, edit and delete tasks for a certain day. Almost every ReactJS Component has been developed from scratch, each task associated with a different color, where each color associated with a different category, to make it easy for the user to differentiate between tasks, also tasks could contain a description, status, and priority. The user can also filter and sort tasks by different conditions.",
            img: "assests/Task Management.png",
            technologies: ["HTML 5", "CSS", "EJS", "NODEJS", "MONGODB","JAVASCRIPT", "BOOTSTRAP"]

        },
        {
            id: "5",
            icon: "assests/web.png",
            title: "Image Captioning",
            desc: "Program that  takes an image as input and produces a relevant caption as output.",
            img: "assests/ImageCaptioning.png",
            technologies: ["HTML 5", "CSS", "EJS", "NODEJS", "JAVASCRIPT"]

        },



    ]


    const handleClick = (way) => {
        console.log(way);
        if (way === "left")
            setCurrentSlide(currentSlide > 0 ? currentSlide - 1 : 2)
        if (way === "right")
            setCurrentSlide(currentSlide < data.length - 1 ? currentSlide + 1 : 0)

    }
    return (
        <div className="works" id="works">
            <div className="slider" style={{ transform: `translateX(-${currentSlide * 100}vw)` }}>

                {data.map((d) => (
                    <div className="container">
                        <div className="item">
                            <div className="left">
                                <div className="leftContainer">
                                    {/* <div className="imgContainer">
                                        <img src={d.icon} alt="" />
                                    </div> */}
                                    <h2>{d.title}</h2>
                                    <p>{d.desc}</p>
                                    <div className ="techWrapper"> 
                                    {d.technologies.map((tech)=> (
                                    <div className="tech"> {tech}</div>
                                    ))}
                                    </div>
                     
                                </div>
                            </div>
                            <div className="right">
                                <img
                                    src={d.img}
                                    alt=""
                                />

                            </div>
                        </div>

                    </div>
                ))}
            </div>
            <img src="assests/whiteArrow.png" className="arrow left" alt="" onClick={() => handleClick("left")} />
            <img src="assests/whiteArrow.png" className="arrow right" alt="" onClick={() => handleClick("right")} />

        </div>
    )
}
